language: emacs-lisp
env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-gtk;
    fi
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
  - cask
script:
  cask exec ecukes
